version: 2.1


jobs:
  update-packages:
    docker:
      - image: circleci/node
    steps:
      - run: |
          curl -X POST https://circleci.com/api/v2/project/github/rbilabs/ctg-connector-service/pipeline \
            -H 'Content-Type: application/json' \
            -H 'Accept: application/json' \
            -H "Circle-Token: $CIRCLECI_TOKEN" \
            -d '{ "branch": "master", "parameters": { "trigger": "update-packages", "version": "latest" } }'
        
# Workflows
workflows:
  master:
    jobs:
      - update-packages:
          filters:
            branches:
              only: master
